# Generated by Django 5.0.2 on 2024-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualorder',
            name='is_hourly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casualorder',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
