# Generated by Django 5.0.2 on 2024-06-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.document', verbose_name='Document Name'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='drop_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_driver', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='pickup_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_driver', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='timesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='employee.timesheet'),
        ),
    ]
