# Generated by Django 5.0.2 on 2024-06-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeetimesheet_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetimesheet',
            options={'ordering': ['duty_start_time']},
        ),
    ]
