# Generated by Django 5.0.2 on 2024-07-31 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_cycle_employeecycle_emplpoyeelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.document', verbose_name='Document Name'),
        ),
    ]
