# Generated by Django 5.0.2 on 2024-08-22 14:40

import src.utils.storage_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(storage=src.utils.storage_file.FileStorage(), upload_to=''),
        ),
    ]
