# Generated by Django 5.0.2 on 2024-09-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_timesheetchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetchangelog',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='employee.employeetimesheet'),
        ),
    ]
