# Generated by Django 5.0.2 on 2024-09-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_casualorder_is_hourly_casualorder_rate_and_more'),
        ('employee', '0013_alter_timesheetchangelog_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimesheet',
            name='timesheet',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='client',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='department',
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
