# Generated by Django 5.0.2 on 2024-09-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeetimesheet_is_invoiced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
