# Generated by Django 5.0.2 on 2024-09-10 07:47

import src.utils.storage_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_delete_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='passport_size_photo',
            field=models.FileField(storage=src.utils.storage_file.FileStorage(), upload_to=''),
        ),
    ]
