# Generated by Django 5.0.2 on 2024-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employeeprofile_passport_size_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimesheet',
            name='verification_status',
            field=models.CharField(choices=[('ROSTER', 'Roster'), ('SUPERVISOR', 'Supervisor'), ('IN_PROCESS', 'In Process'), ('VERIFIED', 'Verified')], default='ROSTER', max_length=10),
        ),
    ]
