# Generated by Django 5.0.2 on 2025-03-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employeetimesheet_duty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetimesheet',
            name='duty_status',
            field=models.CharField(blank=True, choices=[('ABSENT', 'Absent'), ('SICK', 'Sick'), ('LEAVE', 'Leave'), ('PRESENT', 'PRESENT')], max_length=10, null=True),
        ),
    ]
